// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcF577tlQIiVAxdppCT36Ts3jQCF2fMs0',
    appId: '1:654130182816:web:5072e64c0bdf936374a7c5',
    messagingSenderId: '654130182816',
    projectId: 'startingblock-1e512',
    authDomain: 'startingblock-1e512.firebaseapp.com',
    storageBucket: 'startingblock-1e512.firebasestorage.app',
    measurementId: 'G-B5H3GFVG0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPIY6wmd9lFANDsdLh4QzWhNqYC6p4OzI',
    appId: '1:654130182816:android:23c022649791c4da74a7c5',
    messagingSenderId: '654130182816',
    projectId: 'startingblock-1e512',
    storageBucket: 'startingblock-1e512.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7aHYM0qHVzaDC4eFgnWy6boKo5NRW8tY',
    appId: '1:654130182816:ios:92d7fd4098027f3274a7c5',
    messagingSenderId: '654130182816',
    projectId: 'startingblock-1e512',
    storageBucket: 'startingblock-1e512.firebasestorage.app',
    iosBundleId: 'com.synapse.startingBlock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7aHYM0qHVzaDC4eFgnWy6boKo5NRW8tY',
    appId: '1:654130182816:ios:96dda4b35084ce5d74a7c5',
    messagingSenderId: '654130182816',
    projectId: 'startingblock-1e512',
    storageBucket: 'startingblock-1e512.firebasestorage.app',
    iosBundleId: 'com.example.startingBlock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcF577tlQIiVAxdppCT36Ts3jQCF2fMs0',
    appId: '1:654130182816:web:23ad7eccd563ad3474a7c5',
    messagingSenderId: '654130182816',
    projectId: 'startingblock-1e512',
    authDomain: 'startingblock-1e512.firebaseapp.com',
    storageBucket: 'startingblock-1e512.firebasestorage.app',
    measurementId: 'G-FFDJ5RYD2N',
  );
}
